# Generated by Django 4.1.1 on 2022-09-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopitem_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='itemimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
