# Generated by Django 4.1.1 on 2022-09-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
