# Generated by Django 4.1.1 on 2022-09-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='price',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
