# Generated by Django 4.1.1 on 2022-09-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Accounts',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
